/* 
author: Fraser Torning
create date: 10/14/18 
source url: https://nces.ed.gov/surveys/pss/pssdata.asp
*/

create table jrnl_private_school_def (
	PFNLWT float comment 'Final Weight for School',
	REPW1 float comment 'Replicate Weight 1',
	REPW2 float comment 'Replicate Weight 2',
	REPW3 float comment 'Replicate Weight 3',
	REPW4 float comment 'Replicate Weight 4',
	REPW5 float comment 'Replicate Weight 5',
	REPW6 float comment 'Replicate Weight 6',
	REPW7 float comment 'Replicate Weight 7',
	REPW8 float comment 'Replicate Weight 8',
	REPW9 float comment 'Replicate Weight 9',
	REPW10 float comment 'Replicate Weight 10',
	REPW11 float comment 'Replicate Weight 11',
	REPW12 float comment 'Replicate Weight 12',
	REPW13 float comment 'Replicate Weight 13',
	REPW14 float comment 'Replicate Weight 14',
	REPW15 float comment 'Replicate Weight 15',
	REPW16 float comment 'Replicate Weight 16',
	REPW17 float comment 'Replicate Weight 17',
	REPW18 float comment 'Replicate Weight 18',
	REPW19 float comment 'Replicate Weight 19',
	REPW20 float comment 'Replicate Weight 20',
	REPW21 float comment 'Replicate Weight 21',
	REPW22 float comment 'Replicate Weight 22',
	REPW23 float comment 'Replicate Weight 23',
	REPW24 float comment 'Replicate Weight 24',
	REPW25 float comment 'Replicate Weight 25',
	REPW26 float comment 'Replicate Weight 26',
	REPW27 float comment 'Replicate Weight 27',
	REPW28 float comment 'Replicate Weight 28',
	REPW29 float comment 'Replicate Weight 29',
	REPW30 float comment 'Replicate Weight 30',
	REPW31 float comment 'Replicate Weight 31',
	REPW32 float comment 'Replicate Weight 32',
	REPW33 float comment 'Replicate Weight 33',
	REPW34 float comment 'Replicate Weight 34',
	REPW35 float comment 'Replicate Weight 35',
	REPW36 float comment 'Replicate Weight 36',
	REPW37 float comment 'Replicate Weight 37',
	REPW38 float comment 'Replicate Weight 38',
	REPW39 float comment 'Replicate Weight 39',
	REPW40 float comment 'Replicate Weight 40',
	REPW41 float comment 'Replicate Weight 41',
	REPW42 float comment 'Replicate Weight 42',
	REPW43 float comment 'Replicate Weight 43',
	REPW44 float comment 'Replicate Weight 44',
	REPW45 float comment 'Replicate Weight 45',
	REPW46 float comment 'Replicate Weight 46',
	REPW47 float comment 'Replicate Weight 47',
	REPW48 float comment 'Replicate Weight 48',
	REPW49 float comment 'Replicate Weight 49',
	REPW50 float comment 'Replicate Weight 50',
	REPW51 float comment 'Replicate Weight 51',
	REPW52 float comment 'Replicate Weight 52',
	REPW53 float comment 'Replicate Weight 53',
	REPW54 float comment 'Replicate Weight 54',
	REPW55 float comment 'Replicate Weight 55',
	REPW56 float comment 'Replicate Weight 56',
	REPW57 float comment 'Replicate Weight 57',
	REPW58 float comment 'Replicate Weight 58',
	REPW59 float comment 'Replicate Weight 59',
	REPW60 float comment 'Replicate Weight 60',
	REPW61 float comment 'Replicate Weight 61',
	REPW62 float comment 'Replicate Weight 62',
	REPW63 float comment 'Replicate Weight 63',
	REPW64 float comment 'Replicate Weight 64',
	REPW65 float comment 'Replicate Weight 65',
	REPW66 float comment 'Replicate Weight 66',
	REPW67 float comment 'Replicate Weight 67',
	REPW68 float comment 'Replicate Weight 68',
	REPW69 float comment 'Replicate Weight 69',
	REPW70 float comment 'Replicate Weight 70',
	REPW71 float comment 'Replicate Weight 71',
	REPW72 float comment 'Replicate Weight 72',
	REPW73 float comment 'Replicate Weight 73',
	REPW74 float comment 'Replicate Weight 74',
	REPW75 float comment 'Replicate Weight 75',
	REPW76 float comment 'Replicate Weight 76',
	REPW77 float comment 'Replicate Weight 77',
	REPW78 float comment 'Replicate Weight 78',
	REPW79 float comment 'Replicate Weight 79',
	REPW80 float comment 'Replicate Weight 80',
	REPW81 float comment 'Replicate Weight 81',
	REPW82 float comment 'Replicate Weight 82',
	REPW83 float comment 'Replicate Weight 83',
	REPW84 float comment 'Replicate Weight 84',
	REPW85 float comment 'Replicate Weight 85',
	REPW86 float comment 'Replicate Weight 86',
	REPW87 float comment 'Replicate Weight 87',
	REPW88 float comment 'Replicate Weight 88',
	CSOURCE float comment 'Method of Interview',
	P135 float comment '4A Ungraded Offered',
	P140 float comment '4A Ungraded Enrollment',
	P145 float comment '4B Nursery/ Prekindergarten Offered',
	P150 float comment '4B Nursery/ Prekindergarten Enrollment',
	P155 float comment '4C Kindergarten Offered',
	P160 float comment '4C Kindergarten Enrollment',
	P165 float comment '4D Transitional Kindergarten Offered',
	P170 float comment '4D Transitional Kindergarten Enrollment',
	P175 float comment '4E Transitional First Grade Offered',
	P180 float comment '4E Transitional First Grade Enrollment',
	P185 float comment '4F First Grade Offered',
	P190 float comment '4F First Grade Enrollment',
	P195 float comment '4G Second Grade Offered',
	P200 float comment '4G Second Grade Enrollment',
	P205 float comment '4H Third Grade Offered',
	P210 float comment '4H Third Grade Enrollment',
	P215 float comment '4I Fourth Grade Offered',
	P220 float comment '4I Fourth Grade Enrollment',
	P225 float comment '4J Fifth Grade Offered',
	P230 float comment '4J Fifth Grade Enrollment',
	P235 float comment '4K Sixth Grade Offered',
	P240 float comment '4K Sixth Grade Enrollment',
	P245 float comment '4L Seventh Grade Offered',
	P250 float comment '4L Seventh Grade Enrollment',
	P255 float comment '4M Eighth Grade Offered',
	P260 float comment '4M Eighth Grade Enrollment',
	P265 float comment '4N Ninth Grade Offered',
	P270 float comment '4N Ninth Grade Enrollment',
	P275 float comment '4O Tenth Grade Offered',
	P280 float comment '4O Tenth Grade Enrollment',
	P285 float comment '4P Eleventh Grade Offered',
	P290 float comment '4P Eleventh Grade Enrollment',
	P295 float comment '4Q Twelfth Grade Offered',
	P300 float comment '4Q Twelfth Grade Enrollment',
	P305 float comment '5 Total Student Enrollment',
	P320 float comment '6A Hispanic or Latino Students',
	P330 float comment '6B White Students',
	P325 float comment '6C Black Students',
	P316 float comment '6D Asian Students',
	P318 float comment '6E Native Hawaiian/Pacific Islander Students',
	P310 float comment '6F American Indian/Alaska Native Students',
	P332 float comment '6G Students of Two or More Races',
	P335 float comment '7A Is School Coeducational',
	P340 float comment '7B Male Students',
	P345 float comment '8A Students in 12th Grade Last Year',
	P350 float comment '8B Number of 12th Graders Last Year',
	P360 float comment '8D Percent to 4-Year College',
	P365 float comment '9A Length of School Day for Kindergarten',
	P370 float comment '9B Days Per Week for Kindergarten',
	P385 float comment '10 Full-Time Teachers',
	P390 float comment '10 More Than 3/4 Time Teachers',
	P395 float comment '10 More Than 1/2 Time Teachers',
	P400 float comment '10 More Than 1/4 Time Teachers',
	P405 float comment '10 Less Than 1/4 Time Teachers',
	P410 float comment '10 Total Number of Teachers',
	P415 float comment '11 Type of School',
	P420 float comment '12A School Supports Home Schooling',
	P425 float comment '12B Is School Located in Private Home',
	P430 float comment '13A Does School Have Religious Orientation',
	P435 float comment '13B School Affiliation',
	P440 float comment '13C Religious Orientation',
	P445 float comment '13C Type of Catholic School',
	P450 float comment '14 No Associations',
	P455 float comment '14 Accelerated Christian Education',
	P460 float comment '14 American Association of Christian Schools',
	P465 float comment '14 Association of Christian Schools International',
	P467 float comment '14 Association of Christian Teachers and Schools',
	P468 float comment '14 Association of Classical and Christian Schools',
	P470 float comment '14 Christian Schools International',
	P480 float comment '14 Evangelical Lutheran Education Association',
	P485 float comment '14 Friends Council on Education',
	P490 float comment '14 General Conference of SDA Church',
	P492 float comment '14 Islamic School League of America',
	P495 float comment '14 Jesuit Secondary Education Association',
	P500 float comment '14 National Association of Episcopal Schools',
	P505 float comment '14 National Catholic Educational Association',
	P510 float comment '14 National Christian School Association',
	P515 float comment '14 National Society for Hebrew Day Schools',
	P520 float comment '14 Oral Roberts University Educational Fellowship',
	P522 float comment '14 The Jewish Community Day School Network',
	P525 float comment '14 Solomon Schechter Day Schools',
	P530 float comment '14 Southern Baptist Association of Christian Schools',
	P535 float comment '14 Other Religious School Associations',
	P540 float comment '14 American Montessori Society',
	P542 float comment '14 Association Montessori International',
	P545 float comment '14 Other Montessori Associations',
	P550 float comment '14 Association of Military Colleges and Schools',
	P555 float comment '14 Association of Waldorf Schools of North America',
	P575 float comment '14 National Association of Private Special Education Centers',
	P580 float comment '14 Other Associations for Exceptional Children',
	P585 float comment '14 European Council for International Schools',
	P590 float comment '14 National Association for the Education of Young Children',
	P600 float comment '14 National Association of Laboratory Schools',
	P602 float comment '14 National Coalition of Girls\' Schools',
	P605 float comment '14 Other Special Emphasis Associations',
	P610 float comment '14 Alternative School Network',
	P620 float comment '14 National Association of Independent Schools',
	P622 float comment '14 State/Regional Independent School Association',
	P630 float comment '14 National Independent Private Schools Association',
	P635 float comment '14 The Association of Boarding Schools',
	P640 float comment '14 Other School Associations',
	P645 float comment '15 Days in School Year',
	P650 float comment '16 Hours in School Day for Students',
	P655 float comment '16 Minutes in School Day for Students',
	P660 float comment '17 Library or Library Media Center',
	P661 float comment '18A National School Lunch Program',
	P662 float comment '18B Approved for free lunches',
	P663 float comment '19A Title I services',
	P664 float comment '19B Participate in the Title I Program',
	P665 float comment '19B Participate in the Title I Program',
	PPIN VARCHAR(8) comment 'Permanent Identification Number',
	PINST VARCHAR(50) comment 'School Name',
	PADDRS VARCHAR(50) comment 'Mailing Address',
	PCITY VARCHAR(28) comment 'Mailing City',
	PSTABB VARCHAR(2) comment 'Mailing State Postal Code',
	PZIP VARCHAR(5) comment 'Mailing Zip Code',
	PZIP4 VARCHAR(4) comment 'Mailing Zip4 Code',
	PCNTY VARCHAR(3) comment 'ANSI County Code',
	PCNTNM VARCHAR(40) comment 'County Name',
	PL_ADD VARCHAR(50) comment 'Location Address',
	PL_CIT VARCHAR(28) comment 'Location City',
	PL_STABB VARCHAR(2) comment 'Location State Postal Code',
	PL_ZIP VARCHAR(5) comment 'Location Zip Code',
	PL_ZIP4 VARCHAR(4) comment 'Location Zip4 Code',
	REGION float comment 'Census Region',
	PSTANSI float comment 'ANSI State Code (physical location of school)',
	ULOCALE16 float comment 'Urban-centric Locale Code',
	LATITUDE16 float comment 'Latitude',
	LONGITUDE16 float comment 'Longitude',
	SLDLST16 VARCHAR(5) comment 'State Legislative District - Lower',
	SLDUST16 VARCHAR(5) comment 'State Legislative District - Upper',
	STCD16 VARCHAR(4) comment '114th Congressional District',
	LOGR2016 float comment '2015-16 Lowest Grade Level Recode',
	HIGR2016 float comment '2015-16 Highest Grade Level Recode',
	FRAME VARCHAR(4) comment 'Universe frame to which the school belongs',
	TABFLAG float comment 'Tabulation Flag',
	TYPOLOGY float comment 'School Typology',
	RELIG float comment 'Affiliation',
	ORIENT float comment 'School Orientation',
	DIOCESE float comment 'Diocese or archdiocese for Catholic schools',
	`LEVEL` float comment 'Level of Instruction',
	NUMSTUDS float comment 'Total Number of Students in School (K-12, UG)',
	SIZE float comment 'Size of School (K-12, UG)',
	NUMTEACH float comment 'Number of K-12 Teachers (FTE)',
	UCOMMTYP float comment 'Urban-centric Community Type',
	TOTHRS float comment 'Length of School Day in Hours',
	MALES float comment 'Number of Male Students (K-12, UG)',
	F_P135 float comment 'Imputation Flag For P135',
	F_P140 float comment 'Imputation Flag For P140',
	F_P145 float comment 'Imputation Flag For P145',
	F_P150 float comment 'Imputation Flag For P150',
	F_P155 float comment 'Imputation Flag For P155',
	F_P160 float comment 'Imputation Flag For P160',
	F_P165 float comment 'Imputation Flag For P165',
	F_P170 float comment 'Imputation Flag For P170',
	F_P175 float comment 'Imputation Flag For P175',
	F_P180 float comment 'Imputation Flag For P180',
	F_P185 float comment 'Imputation Flag For P185',
	F_P190 float comment 'Imputation Flag For P190',
	F_P195 float comment 'Imputation Flag For P195',
	F_P200 float comment 'Imputation Flag For P200',
	F_P205 float comment 'Imputation Flag For P205',
	F_P210 float comment 'Imputation Flag For P210',
	F_P215 float comment 'Imputation Flag For P215',
	F_P220 float comment 'Imputation Flag For P220',
	F_P225 float comment 'Imputation Flag For P225',
	F_P230 float comment 'Imputation Flag For P230',
	F_P235 float comment 'Imputation Flag For P235',
	F_P240 float comment 'Imputation Flag For P240',
	F_P245 float comment 'Imputation Flag For P245',
	F_P250 float comment 'Imputation Flag For P250',
	F_P255 float comment 'Imputation Flag For P255',
	F_P260 float comment 'Imputation Flag For P260',
	F_P265 float comment 'Imputation Flag For P265',
	F_P270 float comment 'Imputation Flag For P270',
	F_P275 float comment 'Imputation Flag For P275',
	F_P280 float comment 'Imputation Flag For P280',
	F_P285 float comment 'Imputation Flag For P285',
	F_P290 float comment 'Imputation Flag For P290',
	F_P295 float comment 'Imputation Flag For P295',
	F_P300 float comment 'Imputation Flag For P300',
	F_P305 float comment 'Imputation Flag For P305',
	F_P310 float comment 'Imputation Flag For P310',
	F_P316 float comment 'Imputation Flag For P316',
	F_P318 float comment 'Imputation Flag For P318',
	F_P320 float comment 'Imputation Flag For P320',
	F_P325 float comment 'Imputation Flag For P325',
	F_P330 float comment 'Imputation Flag For P330',
	F_P332 float comment 'Imputation Flag For P332',
	F_P335 float comment 'Imputation Flag For P335',
	F_P340 float comment 'Imputation Flag For P340',
	F_P345 float comment 'Imputation Flag For P345',
	F_P350 float comment 'Imputation Flag For P350',
	F_P360 float comment 'Imputation Flag For P360',
	F_P365 float comment 'Imputation Flag For P365',
	F_P370 float comment 'Imputation Flag For P370',
	F_P385 float comment 'Imputation Flag For P385',
	F_P390 float comment 'Imputation Flag For P390',
	F_P395 float comment 'Imputation Flag For P395',
	F_P400 float comment 'Imputation Flag For P400',
	F_P405 float comment 'Imputation Flag For P405',
	F_P410 float comment 'Imputation Flag For P410',
	F_P415 float comment 'Imputation Flag For P415',
	F_P420 float comment 'Imputation Flag For P420',
	F_P425 float comment 'Imputation Flag For P425',
	F_P430 float comment 'Imputation Flag For P430',
	F_P435 float comment 'Imputation Flag For P435',
	F_P440 float comment 'Imputation Flag For P440',
	F_P445 float comment 'Imputation Flag For P445',
	F_P450 float comment 'Imputation Flag For P450',
	F_P455 float comment 'Imputation Flag For P455',
	F_P460 float comment 'Imputation Flag For P460',
	F_P465 float comment 'Imputation Flag For P465',
	F_P467 float comment 'Imputation Flag For P467',
	F_P468 float comment 'Imputation Flag For P468',
	F_P470 float comment 'Imputation Flag For P470',
	F_P480 float comment 'Imputation Flag For P480',
	F_P485 float comment 'Imputation Flag For P485',
	F_P490 float comment 'Imputation Flag For P490',
	F_P492 float comment 'Imputation Flag For P492',
	F_P495 float comment 'Imputation Flag For P495',
	F_P500 float comment 'Imputation Flag For P500',
	F_P505 float comment 'Imputation Flag For P505',
	F_P510 float comment 'Imputation Flag For P510',
	F_P515 float comment 'Imputation Flag For P515',
	F_P520 float comment 'Imputation Flag For P520',
	F_P522 float comment 'Imputation Flag For P522',
	F_P525 float comment 'Imputation Flag For P525',
	F_P530 float comment 'Imputation Flag For P530',
	F_P535 float comment 'Imputation Flag For P535',
	F_P540 float comment 'Imputation Flag For P540',
	F_P542 float comment 'Imputation Flag For P542',
	F_P545 float comment 'Imputation Flag For P545',
	F_P550 float comment 'Imputation Flag For P550',
	F_P555 float comment 'Imputation Flag For P555',
	F_P575 float comment 'Imputation Flag For P575',
	F_P580 float comment 'Imputation Flag For P580',
	F_P585 float comment 'Imputation Flag For P585',
	F_P590 float comment 'Imputation Flag For P590',
	F_P600 float comment 'Imputation Flag For P600',
	F_P602 float comment 'Imputation Flag For P602',
	F_P605 float comment 'Imputation Flag For P605',
	F_P610 float comment 'Imputation Flag For P610',
	F_P620 float comment 'Imputation Flag For P620',
	F_P622 float comment 'Imputation Flag For P622',
	F_P630 float comment 'Imputation Flag For P630',
	F_P635 float comment 'Imputation Flag For P635',
	F_P640 float comment 'Imputation Flag For P640',
	F_P645 float comment 'Imputation Flag For P645',
	F_P650 float comment 'Imputation Flag For P650',
	F_P655 float comment 'Imputation Flag For P655',
	F_P660 float comment 'Imputation Flag For P660',
	F_P661 float comment 'Imputation Flag For P661',
	F_P662 float comment 'Imputation Flag For P662',
	F_P663 float comment 'Imputation Flag For P663',
	F_P664 float comment 'Imputation Flag For P664',
	F_P665 float comment 'Imputation Flag For P665',
	S_KG float comment 'Total Number of Kindergarten Students',
	P_INDIAN float comment 'Percentage of American Indian or Alaskan Native Students',
	P_ASIAN float comment 'Percentage of Asian Students',
	P_PACIFIC float comment 'Percentage of Native Hawaiian or Pacific Islander Students',
	P_HISP float comment 'Percentage of Hispanic Students',
	P_WHITE float comment 'Percentage of White Students',
	P_BLACK float comment 'Percentage of Black Students',
	P_TR float comment 'Percentage of Students of Two or More Races',
	STTCH_RT float comment 'Student Teacher Ratio',
    
    primary key (PPIN),
    index (PPIN),
    index (`LEVEL`),
    index (PL_STABB),
    index (PL_ZIP),
    index (PL_CIT)
);