/* 
author: Fraser Torning
create date: 10/14/18 
source url: https://nces.ed.gov/ccd/pubschuniv.asp
*/

create table {}.jrnl_pub_school_demo_ref (
	SURVYEAR VARCHAR(9) COMMENT 'Year corresponding to survey record',
	FIPST VARCHAR(2) COMMENT 'American National Standards Institute (ANSI) state code',
	STABR VARCHAR(2) COMMENT 'Postal state abbreviation code',
	STATENAME VARCHAR(44) COMMENT 'State name',
	SEANAME VARCHAR(59) COMMENT 'Name of state education agency',
	LEAID VARCHAR(7) COMMENT 'NCES Agency Identification Number',
	ST_LEAID VARCHAR(35) COMMENT 'State Local Education Number. State\'s own ID for the education agency.',
	LEA_NAME VARCHAR(60) COMMENT 'Education Agency Name',
	SCHID VARCHAR(5) COMMENT 'NCES school identifier',
	ST_SCHID VARCHAR(45) COMMENT 'State school identifier',
	NCESSCH VARCHAR(12) COMMENT 'Unique school ID',
	SCH_NAME VARCHAR(60) COMMENT 'School name',
	PK FLOAT COMMENT 'Prekindergarten students',
	KG FLOAT COMMENT 'Kindergarten students',
	G01 FLOAT COMMENT 'Grade 1 students',
	G02 FLOAT COMMENT 'Grade 2 students',
	G03 FLOAT COMMENT 'Grade 3 students',
	G04 FLOAT COMMENT 'Grade 4 students',
	G05 FLOAT COMMENT 'Grade 5 students',
	G06 FLOAT COMMENT 'Grade 6 students',
	G07 FLOAT COMMENT 'Grade 7 students',
	G08 FLOAT COMMENT 'Grade 8 students',
	G09 FLOAT COMMENT 'Grade 9 students',
	G10 FLOAT COMMENT 'Grade 10 students',
	G11 FLOAT COMMENT 'Grade 11 students',
	G12 FLOAT COMMENT 'Grade 12 students',
	G13 FLOAT COMMENT 'Grade 13 students',
	UG FLOAT COMMENT 'Ungraded students',
	AE FLOAT COMMENT 'Total adult education students',
	TOTAL FLOAT COMMENT 'Total students, all grades (includes AE)',
	MEMBER FLOAT COMMENT 'Total elementary/ secondary students (excludes AE)',
	AMPKM FLOAT COMMENT 'PK Students - American Indian/Alaska Native - Male',
	AMPKF FLOAT COMMENT 'PK Students - American Indian/Alaska Native - Female',
	ASPKM FLOAT COMMENT 'PK Students - Asian - Male',
	ASPKF FLOAT COMMENT 'PK Students - Asian - Female',
	HIPKM FLOAT COMMENT 'PK Students - Hispanic - Male',
	HIPKF FLOAT COMMENT 'PK Students - Hispanic - Female',
	BLPKM FLOAT COMMENT 'PK Students - Black - Male',
	BLPKF FLOAT COMMENT 'PK Students - Black - Female',
	WHPKM FLOAT COMMENT 'PK Students - White - Male',
	WHPKF FLOAT COMMENT 'PK Students - White - Female',
	HPPKM FLOAT COMMENT 'PK Students - Hawaiian Native/Pacific Islander - Male',
	HPPKF FLOAT COMMENT 'PK Students - Hawaiian Native/Pacific Islander - Female',
	TRPKM FLOAT COMMENT 'PK Students - Two or More Races - Male',
	TRPKF FLOAT COMMENT 'PK Students - Two or More Races - Female',
	AMKGM FLOAT COMMENT 'KG Students - American Indian/Alaska Native - Male',
	AMKGF FLOAT COMMENT 'KG Students - American Indian/Alaska Native - Female',
	ASKGM FLOAT COMMENT 'KG Students - Asian - Male',
	ASKGF FLOAT COMMENT 'KG Students - Asian - Female',
	HIKGM FLOAT COMMENT 'KG Students - Hispanic - Male',
	HIKGF FLOAT COMMENT 'KG Students - Hispanic - Female',
	BLKGM FLOAT COMMENT 'KG Students - Black - Male',
	BLKGF FLOAT COMMENT 'KG Students - Black - Female',
	WHKGM FLOAT COMMENT 'KG Students - White - Male',
	WHKGF FLOAT COMMENT 'KG Students - White - Female',
	HPKGM FLOAT COMMENT 'KG Students - Hawaiian Native/Pacific Islander - Male',
	HPKGF FLOAT COMMENT 'KG Students - Hawaiian Native/Pacific Islander - Female',
	TRKGM FLOAT COMMENT 'KG Students - Two or More Races - Male',
	TRKGF FLOAT COMMENT 'KG Students - Two or More Races - Female',
	AM01M FLOAT COMMENT 'Grade 1 Students - American Indian/Alaska Native - Male',
	AM01F FLOAT COMMENT 'Grade 1 Students - American Indian/Alaska Native - Female',
	AS01M FLOAT COMMENT 'Grade 1 Students - Asian - Male',
	AS01F FLOAT COMMENT 'Grade 1 Students - Asian - Female',
	HI01M FLOAT COMMENT 'Grade 1 Students - Hispanic - Male',
	HI01F FLOAT COMMENT 'Grade 1 Students - Hispanic - Female',
	BL01M FLOAT COMMENT 'Grade 1 Students - Black - Male',
	BL01F FLOAT COMMENT 'Grade 1 Students - Black - Female',
	WH01M FLOAT COMMENT 'Grade 1 Students - White - Male',
	WH01F FLOAT COMMENT 'Grade 1 Students - White - Female',
	HP01M FLOAT COMMENT 'Grade 1 Students - Hawaiian Native/Pacific Islander - Male',
	HP01F FLOAT COMMENT 'Grade 1 Students - Hawaiian Native/Pacific Islander - Female',
	TR01M FLOAT COMMENT 'Grade 1 Students - Two or More Races - Male',
	TR01F FLOAT COMMENT 'Grade 1 Students - Two or More Races - Female',
	AM02M FLOAT COMMENT 'Grade 2 Students - American Indian/Alaska Native - Male',
	AM02F FLOAT COMMENT 'Grade 2 Students - American Indian/Alaska Native - Female',
	AS02M FLOAT COMMENT 'Grade 2 Students - Asian - Male',
	AS02F FLOAT COMMENT 'Grade 2 Students - Asian - Female',
	HI02M FLOAT COMMENT 'Grade 2 Students - Hispanic - Male',
	HI02F FLOAT COMMENT 'Grade 2 Students - Hispanic - Female',
	BL02M FLOAT COMMENT 'Grade 2 Students - Black - Male',
	BL02F FLOAT COMMENT 'Grade 2 Students - Black - Female',
	WH02M FLOAT COMMENT 'Grade 2 Students - White - Male',
	WH02F FLOAT COMMENT 'Grade 2 Students - White - Female',
	HP02M FLOAT COMMENT 'Grade 2 Students - Hawaiian Native/Pacific Islander - Male',
	HP02F FLOAT COMMENT 'Grade 2 Students - Hawaiian Native/Pacific Islander - Female',
	TR02M FLOAT COMMENT 'Grade 2 Students - Two or More Races - Male',
	TR02F FLOAT COMMENT 'Grade 2 Students - Two or More Races - Female',
	AM03M FLOAT COMMENT 'Grade 3 Students - American Indian/Alaska Native - Male',
	AM03F FLOAT COMMENT 'Grade 3 Students - American Indian/Alaska Native - Female',
	AS03M FLOAT COMMENT 'Grade 3 Students - Asian - Male',
	AS03F FLOAT COMMENT 'Grade 3 Students - Asian - Female',
	HI03M FLOAT COMMENT 'Grade 3 Students - Hispanic - Male',
	HI03F FLOAT COMMENT 'Grade 3 Students - Hispanic - Female',
	BL03M FLOAT COMMENT 'Grade 3 Students - Black - Male',
	BL03F FLOAT COMMENT 'Grade 3 Students - Black - Female',
	WH03M FLOAT COMMENT 'Grade 3 Students - White - Male',
	WH03F FLOAT COMMENT 'Grade 3 Students - White - Female',
	HP03M FLOAT COMMENT 'Grade 3 Students - Hawaiian Native/Pacific Islander - Male',
	HP03F FLOAT COMMENT 'Grade 3 Students - Hawaiian Native/Pacific Islander - Female',
	TR03M FLOAT COMMENT 'Grade 3 Students - Two or More Races - Male',
	TR03F FLOAT COMMENT 'Grade 3 Students - Two or More Races - Female',
	AM04M FLOAT COMMENT 'Grade 4 Students - American Indian/Alaska Native - Male',
	AM04F FLOAT COMMENT 'Grade 4 Students - American Indian/Alaska Native - Female',
	AS04M FLOAT COMMENT 'Grade 4 Students - Asian - Male',
	AS04F FLOAT COMMENT 'Grade 4 Students - Asian - Female',
	HI04M FLOAT COMMENT 'Grade 4 Students - Hispanic - Male',
	HI04F FLOAT COMMENT 'Grade 4 Students - Hispanic - Female',
	BL04M FLOAT COMMENT 'Grade 4 Students - Black - Male',
	BL04F FLOAT COMMENT 'Grade 4 Students - Black - Female',
	WH04M FLOAT COMMENT 'Grade 4 Students - White - Male',
	WH04F FLOAT COMMENT 'Grade 4 Students - White - Female',
	HP04M FLOAT COMMENT 'Grade 4 Students - Hawaiian Native/Pacific Islander - Male',
	HP04F FLOAT COMMENT 'Grade 4 Students - Hawaiian Native/Pacific Islander - Female',
	TR04M FLOAT COMMENT 'Grade 4 Students - Two or More Races - Male',
	TR04F FLOAT COMMENT 'Grade 4 Students - Two or More Races - Female',
	AM05M FLOAT COMMENT 'Grade 5 Students - American Indian/Alaska Native - Male',
	AM05F FLOAT COMMENT 'Grade 5 Students - American Indian/Alaska Native - Female',
	AS05M FLOAT COMMENT 'Grade 5 Students - Asian - Male',
	AS05F FLOAT COMMENT 'Grade 5 Students - Asian - Female',
	HI05M FLOAT COMMENT 'Grade 5 Students - Hispanic - Male',
	HI05F FLOAT COMMENT 'Grade 5 Students - Hispanic - Female',
	BL05M FLOAT COMMENT 'Grade 5 Students - Black - Male',
	BL05F FLOAT COMMENT 'Grade 5 Students - Black - Female',
	WH05M FLOAT COMMENT 'Grade 5 Students - White - Male',
	WH05F FLOAT COMMENT 'Grade 5 Students - White - Female',
	HP05M FLOAT COMMENT 'Grade 5 Students - Hawaiian Native/Pacific Islander - Male',
	HP05F FLOAT COMMENT 'Grade 5 Students - Hawaiian Native/Pacific Islander - Female',
	TR05M FLOAT COMMENT 'Grade 5 Students - Two or More Races - Male',
	TR05F FLOAT COMMENT 'Grade 5 Students - Two or More Races - Female',
	AM06M FLOAT COMMENT 'Grade 6 Students - American Indian/Alaska Native - Male',
	AM06F FLOAT COMMENT 'Grade 6 Students - American Indian/Alaska Native - Female',
	AS06M FLOAT COMMENT 'Grade 6 Students - Asian - Male',
	AS06F FLOAT COMMENT 'Grade 6 Students - Asian - Female',
	HI06M FLOAT COMMENT 'Grade 6 Students - Hispanic - Male',
	HI06F FLOAT COMMENT 'Grade 6 Students - Hispanic - Female',
	BL06M FLOAT COMMENT 'Grade 6 Students - Black - Male',
	BL06F FLOAT COMMENT 'Grade 6 Students - Black - Female',
	WH06M FLOAT COMMENT 'Grade 6 Students - White - Male',
	WH06F FLOAT COMMENT 'Grade 6 Students - White - Female',
	HP06M FLOAT COMMENT 'Grade 6 Students - Hawaiian Native/Pacific Islander - Male',
	HP06F FLOAT COMMENT 'Grade 6 Students - Hawaiian Native/Pacific Islander - Female',
	TR06M FLOAT COMMENT 'Grade 6 Students - Two or More Races - Male',
	TR06F FLOAT COMMENT 'Grade 6 Students - Two or More Races - Female',
	AM07M FLOAT COMMENT 'Grade 7 Students - American Indian/Alaska Native - Male',
	AM07F FLOAT COMMENT 'Grade 7 Students - American Indian/Alaska Native - Female',
	AS07M FLOAT COMMENT 'Grade 7 Students - Asian - Male',
	AS07F FLOAT COMMENT 'Grade 7 Students - Asian - Female',
	HI07M FLOAT COMMENT 'Grade 7 Students - Hispanic - Male',
	HI07F FLOAT COMMENT 'Grade 7 Students - Hispanic - Female',
	BL07M FLOAT COMMENT 'Grade 7 Students - Black - Male',
	BL07F FLOAT COMMENT 'Grade 7 Students - Black - Female',
	WH07M FLOAT COMMENT 'Grade 7 Students - White - Male',
	WH07F FLOAT COMMENT 'Grade 7 Students - White - Female',
	HP07M FLOAT COMMENT 'Grade 7 Students - Hawaiian Native/Pacific Islander - Male',
	HP07F FLOAT COMMENT 'Grade 7 Students - Hawaiian Native/Pacific Islander - Female',
	TR07M FLOAT COMMENT 'Grade 7 Students - Two or More Races - Male',
	TR07F FLOAT COMMENT 'Grade 7 Students - Two or More Races - Female',
	AM08M FLOAT COMMENT 'Grade 8 Students - American Indian/Alaska Native - Male',
	AM08F FLOAT COMMENT 'Grade 8 Students - American Indian/Alaska Native - Female',
	AS08M FLOAT COMMENT 'Grade 8 Students - Asian - Male',
	AS08F FLOAT COMMENT 'Grade 8 Students - Asian - Female',
	HI08M FLOAT COMMENT 'Grade 8 Students - Hispanic - Male',
	HI08F FLOAT COMMENT 'Grade 8 Students - Hispanic - Female',
	BL08M FLOAT COMMENT 'Grade 8 Students - Black - Male',
	BL08F FLOAT COMMENT 'Grade 8 Students - Black - Female',
	WH08M FLOAT COMMENT 'Grade 8 Students - White - Male',
	WH08F FLOAT COMMENT 'Grade 8 Students - White - Female',
	HP08M FLOAT COMMENT 'Grade 8 Students - Hawaiian Native/Pacific Islander - Male',
	HP08F FLOAT COMMENT 'Grade 8 Students - Hawaiian Native/Pacific Islander - Female',
	TR08M FLOAT COMMENT 'Grade 8 Students - Two or More Races - Male',
	TR08F FLOAT COMMENT 'Grade 8 Students - Two or More Races - Female',
	AM09M FLOAT COMMENT 'Grade 9 Students - American Indian/Alaska Native - Male',
	AM09F FLOAT COMMENT 'Grade 9 Students - American Indian/Alaska Native - Female',
	AS09M FLOAT COMMENT 'Grade 9 Students - Asian - Male',
	AS09F FLOAT COMMENT 'Grade 9 Students - Asian - Female',
	HI09M FLOAT COMMENT 'Grade 9 Students - Hispanic - Male',
	HI09F FLOAT COMMENT 'Grade 9 Students - Hispanic - Female',
	BL09M FLOAT COMMENT 'Grade 9 Students - Black - Male',
	BL09F FLOAT COMMENT 'Grade 9 Students - Black - Female',
	WH09M FLOAT COMMENT 'Grade 9 Students - White - Male',
	WH09F FLOAT COMMENT 'Grade 9 Students - White - Female',
	HP09M FLOAT COMMENT 'Grade 9 Students - Hawaiian Native/Pacific Islander - Male',
	HP09F FLOAT COMMENT 'Grade 9 Students - Hawaiian Native/Pacific Islander - Female',
	TR09M FLOAT COMMENT 'Grade 9 Students - Two or More Races - Male',
	TR09F FLOAT COMMENT 'Grade 9 Students - Two or More Races - Female',
	AM10M FLOAT COMMENT 'Grade 10 Students - American Indian/Alaska Native - Male',
	AM10F FLOAT COMMENT 'Grade 10 Students - American Indian/Alaska Native - Female',
	AS10M FLOAT COMMENT 'Grade 10 Students - Asian - Male',
	AS10F FLOAT COMMENT 'Grade 10 Students - Asian - Female',
	HI10M FLOAT COMMENT 'Grade 10 Students - Hispanic - Male',
	HI10F FLOAT COMMENT 'Grade 10 Students - Hispanic - Female',
	BL10M FLOAT COMMENT 'Grade 10 Students - Black - Male',
	BL10F FLOAT COMMENT 'Grade 10 Students - Black - Female',
	WH10M FLOAT COMMENT 'Grade 10 Students - White - Male',
	WH10F FLOAT COMMENT 'Grade 10 Students - White - Female',
	HP10M FLOAT COMMENT 'Grade 10 Students - Hawaiian Native/Pacific Islander - Male',
	HP10F FLOAT COMMENT 'Grade 10 Students - Hawaiian Native/Pacific Islander - Female',
	TR10M FLOAT COMMENT 'Grade 10 Students - Two or More Races - Male',
	TR10F FLOAT COMMENT 'Grade 10 Students - Two or More Races - Female',
	AM11M FLOAT COMMENT 'Grade 11 Students - American Indian/Alaska Native - Male',
	AM11F FLOAT COMMENT 'Grade 11 Students - American Indian/Alaska Native - Female',
	AS11M FLOAT COMMENT 'Grade 11 Students - Asian - Male',
	AS11F FLOAT COMMENT 'Grade 11 Students - Asian - Female',
	HI11M FLOAT COMMENT 'Grade 11 Students - Hispanic - Male',
	HI11F FLOAT COMMENT 'Grade 11 Students - Hispanic - Female',
	BL11M FLOAT COMMENT 'Grade 11 Students - Black - Male',
	BL11F FLOAT COMMENT 'Grade 11 Students - Black - Female',
	WH11M FLOAT COMMENT 'Grade 11 Students - White - Male',
	WH11F FLOAT COMMENT 'Grade 11 Students - White - Female',
	HP11M FLOAT COMMENT 'Grade 11 Students - Hawaiian Native/Pacific Islander - Male',
	HP11F FLOAT COMMENT 'Grade 11 Students - Hawaiian Native/Pacific Islander - Female',
	TR11M FLOAT COMMENT 'Grade 11 Students - Two or More Races - Male',
	TR11F FLOAT COMMENT 'Grade 11 Students - Two or More Races - Female',
	AM12M FLOAT COMMENT 'Grade 12 Students - American Indian/Alaska Native - Male',
	AM12F FLOAT COMMENT 'Grade 12 Students - American Indian/Alaska Native - Female',
	AS12M FLOAT COMMENT 'Grade 12 Students - Asian - Male',
	AS12F FLOAT COMMENT 'Grade 12 Students - Asian - Female',
	HI12M FLOAT COMMENT 'Grade 12 Students - Hispanic - Male',
	HI12F FLOAT COMMENT 'Grade 12 Students - Hispanic - Female',
	BL12M FLOAT COMMENT 'Grade 12 Students - Black - Male',
	BL12F FLOAT COMMENT 'Grade 12 Students - Black - Female',
	WH12M FLOAT COMMENT 'Grade 12 Students - White - Male',
	WH12F FLOAT COMMENT 'Grade 12 Students - White - Female',
	HP12M FLOAT COMMENT 'Grade 12 Students - Hawaiian Native/Pacific Islander - Male',
	HP12F FLOAT COMMENT 'Grade 12 Students - Hawaiian Native/Pacific Islander - Female',
	TR12M FLOAT COMMENT 'Grade 12 Students - Two or More Races - Male',
	TR12F FLOAT COMMENT 'Grade 12 Students - Two or More Races - Female',
	AM13M FLOAT COMMENT 'Grade 13 Students - American Indian/Alaska Native - Male',
	AM13F FLOAT COMMENT 'Grade 13 Students - American Indian/Alaska Native - Female',
	AS13M FLOAT COMMENT 'Grade 13 Students - Asian - Male',
	AS13F FLOAT COMMENT 'Grade 13 Students - Asian - Female',
	HI13M FLOAT COMMENT 'Grade 13 Students - Hispanic - Male',
	HI13F FLOAT COMMENT 'Grade 13 Students - Hispanic - Female',
	BL13M FLOAT COMMENT 'Grade 13 Students - Black - Male',
	BL13F FLOAT COMMENT 'Grade 13 Students - Black - Female',
	WH13M FLOAT COMMENT 'Grade 13 Students - White - Male',
	WH13F FLOAT COMMENT 'Grade 13 Students - White - Female',
	HP13M FLOAT COMMENT 'Grade 13 Students - Hawaiian Native/Pacific Islander - Male',
	HP13F FLOAT COMMENT 'Grade 13 Students - Hawaiian Native/Pacific Islander - Female',
	TR13M FLOAT COMMENT 'Grade 13 Students - Two or More Races - Male',
	TR13F FLOAT COMMENT 'Grade 13 Students - Two or More Races - Female',
	AMUGM FLOAT COMMENT 'Ungraded Students - American Indian/Alaska Native - Male',
	AMUGF FLOAT COMMENT 'Ungraded Students - American Indian/Alaska Native - Female',
	ASUGM FLOAT COMMENT 'Ungraded Students - Asian - Male',
	ASUGF FLOAT COMMENT 'Ungraded Students - Asian - Female',
	HIUGM FLOAT COMMENT 'Ungraded Students - Hispanic - Male',
	HIUGF FLOAT COMMENT 'Ungraded Students - Hispanic - Female',
	BLUGM FLOAT COMMENT 'Ungraded Students - Black - Male',
	BLUGF FLOAT COMMENT 'Ungraded Students - Black - Female',
	WHUGM FLOAT COMMENT 'Ungraded Students - White - Male',
	WHUGF FLOAT COMMENT 'Ungraded Students - White - Female',
	HPUGM FLOAT COMMENT 'Ungraded Students - Hawaiian Native/Pacific Islander - Male',
	HPUGF FLOAT COMMENT 'Ungraded Students - Hawaiian Native/Pacific Islander - Female',
	TRUGM FLOAT COMMENT 'Ungraded Students - Two or More Races - Male',
	TRUGF FLOAT COMMENT 'Ungraded Students - Two or More Races - Female',
	AMAEM FLOAT COMMENT 'Adult Education Students - American Indian/Alaska Native - Male',
	AMAEF FLOAT COMMENT 'Adult Education Students - American Indian/Alaska Native - Female',
	ASAEM FLOAT COMMENT 'Adult Education Students - Asian - Male',
	ASAEF FLOAT COMMENT 'Adult Education Students - Asian - Female',
	HIAEM FLOAT COMMENT 'Adult Education Students - Hispanic - Male',
	HIAEF FLOAT COMMENT 'Adult Education Students - Hispanic - Female',
	BLAEM FLOAT COMMENT 'Adult Education Students - Black - Male',
	BLAEF FLOAT COMMENT 'Adult Education Students - Black - Female',
	WHAEM FLOAT COMMENT 'Adult Education Students - White - Male',
	WHAEF FLOAT COMMENT 'Adult Education Students - White - Female',
	HPAEM FLOAT COMMENT 'Adult Education Students - Hawaiian Native/Pacific Islander - Male',
	HPAEF FLOAT COMMENT 'Adult Education Students - Hawaiian Native/Pacific Islander - Female',
	TRAEM FLOAT COMMENT 'Adult Education Students - Two or More Races - Male',
	TRAEF FLOAT COMMENT 'Adult Education Students - Two or More Races - Female',
	AM FLOAT COMMENT 'All Students - American Indian/Alaska Native',
	AMALM FLOAT COMMENT 'All Students - American Indian/Alaska Native - Male',
	AMALF FLOAT COMMENT 'All Students - American Indian/Alaska Native - Female',
	`AS` FLOAT COMMENT 'All Students - Asian',
	ASALM FLOAT COMMENT 'All Students - Asian - Male',
	ASALF FLOAT COMMENT 'All Students - Asian - Female',
	HI FLOAT COMMENT 'All Students - Hispanic',
	HIALM FLOAT COMMENT 'All Students - Hispanic - Male',
	HIALF FLOAT COMMENT 'All Students - Hispanic - Female',
	BL FLOAT COMMENT 'All Students - Black',
	BLALM FLOAT COMMENT 'All Students - Black - Male',
	BLALF FLOAT COMMENT 'All Students - Black - Female',
	WH FLOAT COMMENT 'All Students - White',
	WHALM FLOAT COMMENT 'All Students - White - Male',
	WHALF FLOAT COMMENT 'All Students - White - Female',
	HP FLOAT COMMENT 'All Students - Hawaiian Native / Pacific Islander',
	HPALM FLOAT COMMENT 'All Students - Hawaiian Native/Pacific Islander - Male',
	HPALF FLOAT COMMENT 'All Students - Hawaiian Native/Pacific Islander - Female',
	TR FLOAT COMMENT 'All Students - Two or More Races',
	TRALM FLOAT COMMENT 'All Students - Two or More Races - Male',
	TRALF FLOAT COMMENT 'All Students - Two or More Races - Female',
  INSERTED_TS TIMESTAMP NOT NULL,
  UPDATED_TS TIMESTAMP NOT NULL,
    
  primary key (NCESSCH),
  index (NCESSCH)
);