from sqlalchemy import Column, String, Float, DateTime
from .base import Base

# https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx


class JrnlCollegeEnrollment(Base):

    __tablename__ = 'jrnl_college_enrollment'.lower()

    UNITID = Column('UNITID', Float, primary_key=True, index=True)
    EFFYLEV = Column('EFFYLEV', Float, primary_key=True)
    LSTUDY = Column('LSTUDY', Float)
    EFYTOTLT = Column('EFYTOTLT', Float)
    EFYTOTLM = Column('EFYTOTLM', Float)
    EFYTOTLW = Column('EFYTOTLW', Float)
    EFYAIANT = Column('EFYAIANT', Float)
    EFYAIANM = Column('EFYAIANM', Float)
    EFYAIANW = Column('EFYAIANW', Float)
    EFYASIAT = Column('EFYASIAT', Float)
    EFYASIAM = Column('EFYASIAM', Float)
    EFYASIAW = Column('EFYASIAW', Float)
    EFYBKAAT = Column('EFYBKAAT', Float)
    EFYBKAAM = Column('EFYBKAAM', Float)
    EFYBKAAW = Column('EFYBKAAW', Float)
    EFYHISPT = Column('EFYHISPT', Float)
    EFYHISPM = Column('EFYHISPM', Float)
    EFYHISPW = Column('EFYHISPW', Float)
    EFYNHPIT = Column('EFYNHPIT', Float)
    EFYNHPIM = Column('EFYNHPIM', Float)
    EFYNHPIW = Column('EFYNHPIW', Float)
    EFYWHITT = Column('EFYWHITT', Float)
    EFYWHITM = Column('EFYWHITM', Float)
    EFYWHITW = Column('EFYWHITW', Float)
    EFY2MORT = Column('EFY2MORT', Float)
    EFY2MORM = Column('EFY2MORM', Float)
    EFY2MORW = Column('EFY2MORW', Float)
    EFYUNKNT = Column('EFYUNKNT', Float)
    EFYUNKNM = Column('EFYUNKNM', Float)
    EFYUNKNW = Column('EFYUNKNW', Float)
    EFYNRALT = Column('EFYNRALT', Float)
    EFYNRALM = Column('EFYNRALM', Float)
    EFYNRALW = Column('EFYNRALW', Float)
    XEYTOTLT = Column('XEYTOTLT', String(1))
    XEYTOTLM = Column('XEYTOTLM', String(1))
    XEYTOTLW = Column('XEYTOTLW', String(1))
    XEFYAIAT = Column('XEFYAIAT', String(1))
    XEFYAIAM = Column('XEFYAIAM', String(1))
    XEFYAIAW = Column('XEFYAIAW', String(1))
    XEFYASIT = Column('XEFYASIT', String(1))
    XEFYASIM = Column('XEFYASIM', String(1))
    XEFYASIW = Column('XEFYASIW', String(1))
    XEFYBKAT = Column('XEFYBKAT', String(1))
    XEFYBKAM = Column('XEFYBKAM', String(1))
    XEFYBKAW = Column('XEFYBKAW', String(1))
    XEFYHIST = Column('XEFYHIST', String(1))
    XEFYHISM = Column('XEFYHISM', String(1))
    XEFYHISW = Column('XEFYHISW', String(1))
    XEFYNHPT = Column('XEFYNHPT', String(1))
    XEFYNHPM = Column('XEFYNHPM', String(1))
    XEFYNHPW = Column('XEFYNHPW', String(1))
    XEFYWHIT = Column('XEFYWHIT', String(1))
    XEFYWHIM = Column('XEFYWHIM', String(1))
    XEFYWHIW = Column('XEFYWHIW', String(1))
    XEFY2MOT = Column('XEFY2MOT', String(1))
    XEFY2MOM = Column('XEFY2MOM', String(1))
    XEFY2MOW = Column('XEFY2MOW', String(1))
    XEYUNKNT = Column('XEYUNKNT', String(1))
    XEYUNKNM = Column('XEYUNKNM', String(1))
    XEYUNKNW = Column('XEYUNKNW', String(1))
    XEYNRALT = Column('XEYNRALT', String(1))
    XEYNRALM = Column('XEYNRALM', String(1))
    XEYNRALW = Column('XEYNRALW', String(1))
    INSERTED_TS = Column("INSERTED_TS", DateTime)
    UPDATED_TS = Column("UPDATED_TS", DateTime)
