from sqlalchemy import Column, String, Float, DateTime
# from config import PROD_FLG, DB_PROD, DB_DEV
from .base import Base


class JrnlPublicSchoolBase(Base):

    __tablename__ = 'jrnl_public_school_base'.lower()
    # if PROD_FLG:
    #     __table_args__ = {'schema': DB_PROD['schema']}
    # else:
    #     __table_args__ = {'schema': DB_DEV['schema']}

    SCHOOL_YEAR = Column('SCHOOL_YEAR', String(9))
    FIPST = Column('FIPST', String(2))
    STATENAME = Column('STATENAME', String(44))
    ST = Column('ST', String(2))
    SCH_NAME = Column('SCH_NAME', String(60))
    LEA_NAME = Column('LEA_NAME', String(60))
    STATE_AGENCY_NO = Column('STATE_AGENCY_NO', String(3))
    UNION = Column('UNION', String(3))
    ST_LEAID = Column('ST_LEAID', String(35))
    LEAID = Column('LEAID', String(7))
    ST_SCHID = Column('ST_SCHID', String(45))
    NCESSCH = Column('NCESSCH', String(12), primary_key=True, index=True)
    SCHID = Column('SCHID', String(7))
    MSTREET1 = Column('MSTREET1', String(60))
    MSTREET2 = Column('MSTREET2', String(30))
    MSTREET3 = Column('MSTREET3', String(30))
    MCITY = Column('MCITY', String(30))
    MSTATE = Column('MSTATE', String(2))
    MZIP = Column('MZIP', String(5))
    MZIP4 = Column('MZIP4', String(4))
    LSTREET1 = Column('LSTREET1', String(60))
    LSTREET2 = Column('LSTREET2', String(30))
    LSTREET3 = Column('LSTREET3', String(30))
    LCITY = Column('LCITY', String(30))
    LSTATE = Column('LSTATE', String(2))
    LZIP = Column('LZIP', String(5))
    LZIP4 = Column('LZIP4', String(4))
    PHONE = Column('PHONE', String(13))
    WEBSITE = Column('WEBSITE', String(120))
    SY_STATUS = Column('SY_STATUS', String(1))
    SY_STATUS_TEXT = Column('SY_STATUS_TEXT', String(30))
    UPDATED_STATUS = Column('UPDATED_STATUS', String(1))
    UPDATED_STATUS_TEXT = Column('UPDATED_STATUS_TEXT', String(30))
    EFFECTIVE_DATE = Column('EFFECTIVE_DATE', String(20))
    SCH_TYPE = Column('SCH_TYPE', String(1))
    SCH_TYPE_TEXT = Column('SCH_TYPE_TEXT', String(28))
    RECON_STATUS = Column('RECON_STATUS', String(3))
    OUT_OF_STATE_FLAG = Column('OUT_OF_STATE_FLAG', String(3))
    CHARTER_TEXT = Column('CHARTER_TEXT', String(14))
    CHARTAUTH1 = Column('CHARTAUTH1', String(60))
    CHARTAUTHN1 = Column('CHARTAUTHN1', String(30))
    CHARTAUTH2 = Column('CHARTAUTH2', String(60))
    CHARTAUTHN2 = Column('CHARTAUTHN2', String(30))
    NOGRADES = Column('NOGRADES', String(12))
    G_PK_OFFERED = Column('G_PK_OFFERED', String(12))
    G_KG_OFFERED = Column('G_KG_OFFERED', String(12))
    G_1_OFFERED = Column('G_1_OFFERED', String(12))
    G_2_OFFERED = Column('G_2_OFFERED', String(12))
    G_3_OFFERED = Column('G_3_OFFERED', String(12))
    G_4_OFFERED = Column('G_4_OFFERED', String(12))
    G_5_OFFERED = Column('G_5_OFFERED', String(12))
    G_6_OFFERED = Column('G_6_OFFERED', String(12))
    G_7_OFFERED = Column('G_7_OFFERED', String(12))
    G_8_OFFERED = Column('G_8_OFFERED', String(12))
    G_9_OFFERED = Column('G_9_OFFERED', String(12))
    G_10_OFFERED = Column('G_10_OFFERED', String(12))
    G_11_OFFERED = Column('G_11_OFFERED', String(12))
    G_12_OFFERED = Column('G_12_OFFERED', String(12))
    G_13_OFFERED = Column('G_13_OFFERED', String(12))
    G_UG_OFFERED = Column('G_UG_OFFERED', String(12))
    G_AE_OFFERED = Column('G_AE_OFFERED', String(12))
    GSLO = Column('GSLO', String(2))
    GSHI = Column('GSHI', String(2))
    LEVEL = Column('LEVEL', String(16))
    IGOFFERED = Column('IGOFFERED', String(14))
    INSERTED_TS = Column("INSERTED_TS", DateTime)
    UPDATED_TS = Column("UPDATED_TS", DateTime)
