from sqlalchemy import Column, String, Float, DateTime
from .base import Base

# https://nces.ed.gov/ipeds/datacenter/DataFiles.aspx


class JrnlCollegeBase(Base):

    __tablename__ = 'jrnl_college_base'.lower()

    UNITID = Column('UNITID', Float, primary_key=True, index=True)
    INSTNM = Column('INSTNM', String(120))
    IALIAS = Column('IALIAS', String(2000))
    ADDR = Column('ADDR', String(100))
    CITY = Column('CITY', String(30))
    STABBR = Column('STABBR', String(2))
    ZIP = Column('ZIP', String(10))
    FIPS = Column('FIPS', Float)
    OBEREG = Column('OBEREG', Float)
    CHFNM = Column('CHFNM', String(50))
    CHFTITLE = Column('CHFTITLE', String(50))
    GENTELE = Column('GENTELE', String(15))
    EIN = Column('EIN', String(9))
    DUNS = Column('DUNS', String(2000))
    OPEID = Column('OPEID', String(8))
    OPEFLAG = Column('OPEFLAG', Float)
    WEBADDR = Column('WEBADDR', String(150))
    ADMINURL = Column('ADMINURL', String(200))
    FAIDURL = Column('FAIDURL', String(200))
    APPLURL = Column('APPLURL', String(200))
    NPRICURL = Column('NPRICURL', String(200))
    VETURL = Column('VETURL', String(200))
    ATHURL = Column('ATHURL', String(150))
    DISAURL = Column('DISAURL', String(200))
    SECTOR = Column('SECTOR', Float)
    ICLEVEL = Column('ICLEVEL', Float)
    CONTROL = Column('CONTROL', Float)
    HLOFFER = Column('HLOFFER', Float)
    UGOFFER = Column('UGOFFER', Float)
    GROFFER = Column('GROFFER', Float)
    HDEGOFR1 = Column('HDEGOFR1', Float)
    DEGGRANT = Column('DEGGRANT', Float)
    HBCU = Column('HBCU', Float)
    HOSPITAL = Column('HOSPITAL', Float)
    MEDICAL = Column('MEDICAL', Float)
    TRIBAL = Column('TRIBAL', Float)
    LOCALE = Column('LOCALE', Float)
    OPENPUBL = Column('OPENPUBL', Float)
    ACT = Column('ACT', String(1))
    NEWID = Column('NEWID', Float)
    DEATHYR = Column('DEATHYR', Float)
    CLOSEDAT = Column('CLOSEDAT', String(10))
    CYACTIVE = Column('CYACTIVE', Float)
    POSTSEC = Column('POSTSEC', Float)
    PSEFLAG = Column('PSEFLAG', Float)
    PSET4FLG = Column('PSET4FLG', Float)
    RPTMTH = Column('RPTMTH', Float)
    INSTCAT = Column('INSTCAT', Float)
    C15BASIC = Column('C15BASIC', Float)
    C15IPUG = Column('C15IPUG', Float)
    C15IPGRD = Column('C15IPGRD', Float)
    C15UGPRF = Column('C15UGPRF', Float)
    C15ENPRF = Column('C15ENPRF', Float)
    C15SZSET = Column('C15SZSET', Float)
    CCBASIC = Column('CCBASIC', Float)
    CARNEGIE = Column('CARNEGIE', Float)
    LANDGRNT = Column('LANDGRNT', Float)
    INSTSIZE = Column('INSTSIZE', Float)
    F1SYSTYP = Column('F1SYSTYP', Float)
    F1SYSNAM = Column('F1SYSNAM', String(80))
    F1SYSCOD = Column('F1SYSCOD', String(6))
    CBSA = Column('CBSA', Float)
    CBSATYPE = Column('CBSATYPE', Float)
    CSA = Column('CSA', Float)
    NECTA = Column('NECTA', Float)
    COUNTYCD = Column('COUNTYCD', Float)
    COUNTYNM = Column('COUNTYNM', String(30))
    CNGDSTCD = Column('CNGDSTCD', Float)
    LONGITUD = Column('LONGITUD', Float)
    LATITUDE = Column('LATITUDE', Float)
    INSERTED_TS = Column("INSERTED_TS", DateTime)
    UPDATED_TS = Column("UPDATED_TS", DateTime)
